"""auto: soccer tables

Revision ID: 0b0fb89b9e3a
Revises: 2a52d5d72a81
Create Date: 2026-01-26 17:11:45.642717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0fb89b9e3a'
down_revision: Union[str, None] = '2a52d5d72a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

