"""auto: soccer tables

Revision ID: 0c23a3c52f04
Revises: 80fbda3a36ba
Create Date: 2026-01-26 16:50:18.031142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c23a3c52f04'
down_revision: Union[str, None] = '80fbda3a36ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

