"""auto: soccer tables

Revision ID: 11bb95bb4dc7
Revises: 6128a7e6b238
Create Date: 2026-01-26 16:56:48.490889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bb95bb4dc7'
down_revision: Union[str, None] = '6128a7e6b238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

