"""auto: soccer tables

Revision ID: 14c27f3cbd10
Revises: eb8bc2174ed3
Create Date: 2026-01-26 17:04:32.317981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c27f3cbd10'
down_revision: Union[str, None] = 'eb8bc2174ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

