"""auto: soccer tables

Revision ID: 1e5286bd8e88
Revises: 14c27f3cbd10
Create Date: 2026-01-26 17:04:40.366109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5286bd8e88'
down_revision: Union[str, None] = '14c27f3cbd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

