"""auto: soccer tables

Revision ID: 2908b7291b0a
Revises: 9a1f8cf85234
Create Date: 2026-01-26 16:50:50.942256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2908b7291b0a'
down_revision: Union[str, None] = '9a1f8cf85234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

