"""auto: soccer tables

Revision ID: 2a52d5d72a81
Revises: 2aeb4c145fe4
Create Date: 2026-01-26 17:11:37.741039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a52d5d72a81'
down_revision: Union[str, None] = '2aeb4c145fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

