"""auto: soccer tables

Revision ID: 2aeb4c145fe4
Revises: 9b87bdbf2e95
Create Date: 2026-01-26 17:11:29.761115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aeb4c145fe4'
down_revision: Union[str, None] = '9b87bdbf2e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

