"""auto: soccer tables

Revision ID: 2dafae8b30bc
Revises: f5f1df0237d8
Create Date: 2026-01-26 17:03:44.382560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dafae8b30bc'
down_revision: Union[str, None] = 'f5f1df0237d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

