"""auto: soccer tables

Revision ID: 3293422d37d1
Revises: 1f4ddf6f6f33
Create Date: 2026-01-26 17:04:16.289985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3293422d37d1'
down_revision: Union[str, None] = '1f4ddf6f6f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

