"""auto: soccer tables

Revision ID: 48f89b6317e8
Revises: dfc4ca00bb71
Create Date: 2026-01-26 17:05:28.713893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f89b6317e8'
down_revision: Union[str, None] = 'dfc4ca00bb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

