"""auto: soccer tables

Revision ID: 4a7cbb6f65bd
Revises: e300d23584f1
Create Date: 2026-01-26 17:11:13.959009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7cbb6f65bd'
down_revision: Union[str, None] = 'e300d23584f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

