"""auto: soccer tables

Revision ID: 4b62672a9df7
Revises: 3fe50ad2b96b
Create Date: 2026-01-26 16:52:37.490090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b62672a9df7'
down_revision: Union[str, None] = '3fe50ad2b96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

