"""auto: soccer tables

Revision ID: 54d0fe2fa553
Revises: 0b0fb89b9e3a
Create Date: 2026-01-26 17:11:53.831552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d0fe2fa553'
down_revision: Union[str, None] = '0b0fb89b9e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

