"""auto: soccer tables

Revision ID: 6c4f17f6fdfa
Revises: 9064bb961a18
Create Date: 2026-01-26 16:52:12.417897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4f17f6fdfa'
down_revision: Union[str, None] = '9064bb961a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

