"""create player embeddings table

Revision ID: 74dac800b7ed
Revises: fce11f1a8cc6
Create Date: 2026-02-02 14:34:33.148324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '74dac800b7ed'
down_revision: Union[str, None] = 'fce11f1a8cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='임베딩 레코드 고유 식별자'),
    sa.Column('stadium_id', sa.BigInteger(), nullable=False, comment='경기장 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='임베딩 생성에 사용된 원본 텍스트'),
    sa.Column('embedding', Vector(768), nullable=False, comment='768차원 임베딩 벡터 (KoElectra)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시간'),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='임베딩 레코드 고유 식별자'),
    sa.Column('team_id', sa.BigInteger(), nullable=False, comment='팀 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='임베딩 생성에 사용된 원본 텍스트'),
    sa.Column('embedding', Vector(768), nullable=False, comment='768차원 KoElectra 임베딩 벡터'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시간'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='임베딩 레코드 고유 식별자'),
    sa.Column('player_id', sa.BigInteger(), nullable=False, comment='선수 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='임베딩 생성에 사용된 원본 텍스트'),
    sa.Column('embedding', Vector(768), nullable=False, comment='768차원 KoElectra 임베딩 벡터'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시간'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='임베딩 레코드 고유 식별자'),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False, comment='경기 일정 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='임베딩 생성에 사용된 원본 텍스트'),
    sa.Column('embedding', Vector(768), nullable=False, comment='768차원 KoElectra 임베딩 벡터'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시간'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_embeddings')
    op.drop_table('player_embeddings')
    op.drop_table('team_embeddings')
    op.drop_table('stadium_embeddings')
    # ### end Alembic commands ###

