"""auto: soccer tables

Revision ID: 7d2dd1fcaa51
Revises: edc3a6054d1d
Create Date: 2026-01-26 17:02:20.018680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2dd1fcaa51'
down_revision: Union[str, None] = 'edc3a6054d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

