"""auto: soccer tables

Revision ID: 971b201d1f2b
Revises: 5d2b8b621eb5
Create Date: 2026-01-26 17:09:18.404451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971b201d1f2b'
down_revision: Union[str, None] = '5d2b8b621eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

