"""auto: soccer tables

Revision ID: 9b87bdbf2e95
Revises: 4a7cbb6f65bd
Create Date: 2026-01-26 17:11:21.825653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b87bdbf2e95'
down_revision: Union[str, None] = '4a7cbb6f65bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

