"""auto: soccer tables

Revision ID: d3b2b78fbefa
Revises: 6e9b67d72c73
Create Date: 2026-01-26 17:04:56.433191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b2b78fbefa'
down_revision: Union[str, None] = '6e9b67d72c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

