"""auto: soccer tables

Revision ID: dd7ec6b0f2b4
Revises: 0c23a3c52f04
Create Date: 2026-01-26 16:50:26.291158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7ec6b0f2b4'
down_revision: Union[str, None] = '0c23a3c52f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

